### ISSUE TITLE
App crash when mysql connection get lost

### ISSUE THREAD

**Issue by edisaac** [jrichardsz/oauth2-shield#15]
Al parecer por inactividad el servidor cierra la conexion a la base de datos, y el container se detiene.

> 
> db error Error: Connection lost: The server closed the connection.
>     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
>     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
>     at Socket.emit (events.js:214:15)
>     at endReadableNT (_stream_readable.js:1178:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   fatal: true,
>   code: 'PROTOCOL_CONNECTION_LOST'
> }
> /app/database/DatabaseConnection.js:77
>         throw err;
>         ^
> 
> Error: Connection lost: The server closed the connection.
>     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:109:13)
>     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
>     at Socket.emit (events.js:214:15)
>     at endReadableNT (_stream_readable.js:1178:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   fatal: true,
>   code: 'PROTOCOL_CONNECTION_LOST'
> }

**Comment by jrichardsz** [comment]
What would be the expected behavior?
If database is down, the application will show unexpected behaviors.
I will review how to preserve the application or maybe a flag called "survive_on_db_down" but, if you are created a client, you cannot validate it without database.

**Comment by jrichardsz** [comment]
Hi. This is the explanation  of your detected issue:

> Previos version of **oauth2-shield** crash when lose the connection to a MySQL server due to network problems, the database server timing you out, the database server being restarted. 

- https://github.com/mysqljs/mysql#server-disconnects
- https://stackoverflow.com/questions/20210522/nodejs-mysql-error-connection-lost-the-server-closed-the-connection

So if is just a temporary database problem or restarting, this [pull request](https://github.com/jrichardsz/oauth2-shield/pull/17) fix it
